### ISSUE TITLE
Add topic tag

### ISSUE THREAD

**Issue by Beliavsky** [nbehrnd/bader_article#1]
Thanks for doing this.

I suggest adding the topic tag `fortran` and mentioning that Bader is deceased, so that a reader will understand why you are editing his article. You could replace

"draft prepared by Reinhold Bader intended"

with

"draft prepared by the late Reinhold Bader intended"

**Comment by nbehrnd** [comment]
@Beliavsky Thank your for your suggestion to complement the action leading to set up the project and leading to the first commit.  Because of the content, the additional tag `Fortran90` seemed justified.
